services:
  - type: web
    name: resume-matcher
    env: python
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: python app/main.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app/main.py
